### ISSUE TITLE
Incorrect aggro type

### ISSUE THREAD

**Issue by Aireil** [Strati/DeepDungeonDex#1]
NameId: 7327
Currently sight => sound.
https://i.imgur.com/OabKLmh.png

NameId: 7328
Currently proximity => sound.
https://i.imgur.com/lORjVG1.png

NameId: 7330
Currently proximity => sight.
https://i.imgur.com/o9n2tWj.png

**Comment by Strati** [comment]
Closed by #2. Thanks!
