### ISSUE TITLE
New info regarding Info Add (Floors 1 to 10)

### ISSUE THREAD

**Issue by Cramoisi-San** [Strati/DeepDungeonDex#12]
Palace Deathmouse/Ziz/Antelope/Bat/Coblyn/Beetle/Dung Bettle/Hornet/Yarzon, Lost Goblin: Stunnable

**Comment by Cramoisi-San** [comment]
Misc: Palace Beetle can Poison

**Comment by Strati** [comment]
Added notes and changed things accordingly. Thanks!
