### ISSUE TITLE
New info regarding Info Add (Floors 11 to 20)

### ISSUE THREAD

**Issue by Cramoisi-San** [Strati/DeepDungeonDex#13]
Palace Urganite/Toad/Slime/Cobra/Ninki Nanka/Nanka/Ochu/Seedling/Morbol, Living Whelk: Stunnable
Staff Spinning Adventurer, Palace Biloko: Non-Stunnable
Misc: Palace Urganite can poison; Palace Pudding can increase it's own magic attack; Palace Cobra can petrify, proposal to change rank into Danger; Palace Ochu can AoE slow; Palace Seedling can do stackable poison, proposal to upgrade rank into caution

**Comment by Strati** [comment]
I've taken your suggestions into consideration and I agree, so I adjusted the threat level on those accordingly and added notes where applicable. Thanks!
