### ISSUE TITLE
Heavenly Tetsu-kyojin description should include it's high damage/insta kill line aoe

### ISSUE THREAD

**Issue by Goreman12** [Strati/DeepDungeonDex#15]
Was playing DRG in solo HoH and got hit by it's line aoe which 1 hit killed me. Not sure if tanks can survive it, but it killed me at around 90% hp.

**Comment by Strati** [comment]
I'm sorry your run ended that way. However, I think "don't get hit by telegraphed aoes on higher floor sets because there is a good chance they will one-shot" should be implicitly understood by Deep Dungeon players, and seems superfluous to add.
