### ISSUE TITLE
Wrong skill on Floor 40 boss info 

### ISSUE THREAD

**Issue by Pr0num** [Strati/DeepDungeonDex#3]
Hello!
DDD says Bhima casts a half-roomwide AOE. He casts a line AOE after the knockback, then repeats it's pattern (targeted circle AOE, knockback, line AOE.)

[Maygi's guide](https://docs.google.com/document/d/1YVBSTOgJO-xOAB6YyKZEZRikjXFPle6Ihf_E7VdmQnI/preview#bookmark=id.ewat3kclbdh7) also says nothing about a half-roomwide.

Maybe it's just phrasing, but for previous floors bosses, half-roomwides actually meant get behind the boss.

**Comment by Strati** [comment]
Weird that that slipped in there and went unnoticed for so long. I blame hasty editing when I was first writing the short descriptions for the plugin. 😅 I'll revise, thanks for bringing it up!

**Comment by Strati** [comment]
Revised description in 8bdd1c0.
