### ISSUE TITLE
Some invalid aggro types

### ISSUE THREAD

**Issue by Tancred423** [Strati/DeepDungeonDex#8]
Hi, great plugin and thanks for making it. I found some invalid aggro types tho:

Deep Palace Slime is "Sound", not "Proximity". [Proof](https://tanc.red/share/2021_09_12_Z79qq5W9EZ.mp4)
Deep Palace Salamander is "Sound", not "Sight". [Proof](https://tanc.red/share/2021_09_12_viElbhc9ST.mp4)
Deep Palace Monk is "Proximity", not "Sight". [Proof](https://tanc.red/share/2021_09_12_nujPIQ1ZCc.mp4)
Deep Palace Soul is "Sound", not "Sight". [Proof](https://tanc.red/share/2021_09_12_m5eVODVt1v.mp4)
Deep Palace Bhoot is "Sound", not "Sight". [Proof](https://tanc.red/share/2021_09_12_1rIVr8OnUN.mp4)

Probably same for the non deep versions but untested. Except Monks. I tested those and they are also Proximity.

**Comment by Tancred423** [comment]
New find:
Palace Roselet is "Sound", not "Proximity". [Proof](https://tanc.red/share/2021_09_14_N2vY5otaP2.mp4) - Should also be the case for their equivalent Deep Palace Trap.

**Comment by quisquous** [comment]
Deep Palace Hecteyes (seen on level 131) is also sound (despite having eyes in the name).

**Comment by Strati** [comment]
I've adjusted these accordingly in the latest update. Thanks for reporting them
